package us.noop.server;

import java.util.ArrayList;
import java.util.HashMap;

/**
 * A class to manage the Response Threads generated by the server, mainly closing them and removing excess.
 * Also organizes responses based on pages.
 * 
 * Possibly a bad idea.
 * @author ing_unfootemcnabb
 *
 */
public class ResponseManager {
	
	private ArrayList<Thread> responses = new ArrayList<Thread>();
	
	/**
	 * Adds a Response thread to monitor.
	 * @param t the thread
	 */
	public void register(Thread t){
		responses.add(t);
	}
	
	private HashMap<String, Page> pages = new HashMap<String, Page>();
	
	/**
	 * Returns an appropriate response to the address.
	 * Pages are registered in Server
	 * @param address the address passed by the client
	 * @return a page
	 */
	public String getResponse(String address){
		address = address.trim();
		int i = 0;
		String currentR = null;
		for(String s : pages.keySet()){
			if(address.startsWith(s)){
				if(s.split("/").length >= i){
					i = s.split("/").length;
					currentR = s;
				}
			}
		}
		String r = "";
		if(currentR == null) r = "Invalid address.";
		else r = pages.get(currentR).getResponse(address);
		return "HTTP/1.1 200 OK\r\nContent-Length: " + r.length() + "\r\nConnection: Closed\r\nContent-Type: " + pages.get(currentR).mimeType() + "\r\n\r\n" + r;
	}
	
	/**
	 * Adds a page that will be a valid request
	 * @param p the page to add (the address should be contained in the class)
	 */
	public void addPage(Page p){
		pages.put(p.getAddress(), p);
	}
	
	private int id = 0;
	
	/**
	 * A utility method to make Responses easier to display in console.
	 * @return the next unused id
	 */
	public int nextId(){
		id++;
		return id - 1;
		
	}
}
